#main.yml file

name: Code Quality Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  flake8:
    name: Flake8 Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82,F841 --show-source --statistics
